<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$_attributeValue = 'Packaging wrapped out';
?>
 
<?php if ($_attributeValue): ?>
    <div class="packaging-content" <?php  echo $_attributeAddAttribute;?>>
    </div>
<?php endif; ?>

<?php if ($_code == 'documentation'): ?>
    <?php echo $_product->getDocumentation(); ?>
<?php elseif ($_code == 'applications'): ?>
    <?php echo $_product->getApplications(); ?>
<?php endif; ?>