<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>503 page</title>
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
        }

        .error-wrapper {
            text-align: center;
            position: relative;
        }

        .error-img {
            width: 100%;
            height: 100%;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            object-fit: cover;
        }

        @media only screen and (max-width: 1024px) {
            .error-img {
                object-fit: cover;
            }
        }
    </style>
</head>
<body>
<div class="error-wrapper">
    <img class="error-img" src="images/503/maintain.png" alt="fecon">
</div>
</body>
</html>


