version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13
    ports:
      - 8020:8000
      - 8070:8443
    depends_on:
      - cron
    links:
      - db
      - phpfpm
      - redis
      - mailcatcher
    volumes: &appvolumes
      - ./:/var/www/html
      - ~/.composer:/var/www/html/var/composer_home
      - sockdata:/sock
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-certs:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:7.1-fpm
    links:
      - phpmyadmin
      - mailcatcher
    depends_on:
      - phpmyadmin
    volumes: *appvolumes    
    networks:
      default:
        aliases:
          - phpfpm

  cron:
    image: markoshust/magento-php:7.1-fpm
    depends_on:
      - phpfpm
    user: root
    command: /usr/local/bin/cronstart
    links:
      - phpfpm
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: mysql:5.7
    ports:
      - 800:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  varnish:
    image: million12/varnish
    links:
      - app
      - phpfpm
    depends_on:
      - simplesamlphpsp
    ports:
      - 8030:80
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
    environment:
      - VLC_CONFIG=/etc/varnish/default.vcl
    networks:
      default:
        aliases:
          - varnish

  mailcatcher:
    image: tophfr/mailcatcher
    depends_on:
      - redis
    ports:
        - 8040:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mailcatcher
    links:
        - db
    ports:
        - 8050:80
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=s3rf3ntr4nd0

  redis:
    image: redis:alpine
    depends_on:
      - db

  simplesamlphpsp:
    image: cirrusid/ssp-base
    ports:
      - 8060:443
    volumes:
      - ./spconfig:/var/simplesamlphp/config
      - ./spmetadata:/var/simplesamlphp/metadata
    depends_on:
      - app
volumes:
  dbdata:
  sockdata:
