<?php
/**
 * Social Feed Template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<h2>Social Feeds</h2>
<div id="instafeed" class="owl-carousel owl-theme owl-bottom-narrow"></div>

<script>
require(['Instafeed', 'jquery', 'owl.carousel/owl.carousel.min'], function(Instafeed, $) {
    var userId = 573020768;
    var token = '573020768.547f12f.d4522e618297412ca3cd7c146d891d80';
    var igUsername;
    var profile_picture;
    //$('.ig-btn').on('click', function () {
    //    alert("");
    //    if ($(this).attr('data-type') == 'video') {
    //        window.open(
    //          $(this).attr('data-link'),
    //          '_blank' // <- This is what makes it open in a new window.
    //        );

    //    } else {
    //        $('#ig-modal').find('.modal-body').html();
    //    }
    //});

    // $.ajax({
    //     url: 'https://api.instagram.com/v1/users/' + userId + '/?access_token=' + token,
    //     success: function (data) {
    //         profile_picture = data.data.profile_picture;
    //         $('.ig-header-profile').find('img').attr("src", profile_picture);
    //         igUsername = data.data.username;

    //         $('.ig-username').html(igUsername);
    //         $('.ig-link').attr("href", 'https://www.instagram.com/' + igUsername);
    //     }
    // });



    var feed = new Instafeed({
        get: 'user',
        userId: userId,
        accessToken: token,
        resolution: 'standard_resolution',
        //filter: function(image) {
        //    if( image.type === 'video')
        //    {
        //        console.log(image);
        //    }
        //    return true;
        //},
        template: '<div class="item clear"><a href="" data-type="{{type}}" data-link="{{link}}" class="ig-btn" data-desc="{{caption}}" data-likes="{{likes}}" data-comments="{{comments}}" data-links="{{link}}"><img src="{{image}}" />' +
        '<div class="ig-overlay"><div class="ig-template"><i class="ig-icon {{type}}"> </i><div class="ig-overlay-text">{{caption}}</div></div></div>' + '</a></div>',
        after: function () {
            // disable button if no more results to load
            //if (!this.hasNext()) {
            //    btnInstafeedLoad.setAttribute('disabled', 'disabled');
            //}

            var owl = $("#instafeed"),
                owlSlideSpeed = 300;

            // init owl    
            $(document).ready(function () {
                owl.owlCarousel({
                    // navContainer: '.owl-nav-custom',
                    // dotsContainer: '.owl-dots-custom',
                    //items: 4,
                    itemsDesktop: [1199, 5],
                    itemsDesktopSmall: [979, 4],
                    itemsTablet: [768, 4],
                    itemsMobile: [479, 3],
                    pagination: false,
                    responsiveRefreshRate: 100,
                    lazyLoad: true,
                    loop: true,
                    margin: 10,
                    nav: false
                });
            });
        }
    });
    feed.run();

    var currentSlide;
    $('body').on('click', '.ig-btn', function (e) {
        e.preventDefault();
        currentSlide = this;

        $('.ig-follow-link').attr("href", $(this).data("links"));
        $('.ig-article-image').fadeOut(200, function () {
            $('.ig-article-image').attr("src", $(currentSlide).children().attr("src"));

        })
        .fadeIn(400);
        if ($(this).data('type') == 'video') {
            $('.ig-img-holder').addClass("video-holder");
            if ($('.video-btn').length == 0) {
                $('.ig-img-holder').prepend('<i class="ig-icon video video-btn"> </i>');
            }
        }
        else {
            $('.video-btn').remove();
            $('.ig-img-holder').removeClass("video-holder");
        }
        $(".ig-description").html($(this).data("desc"));
        $('.ig-likes').html('<i class="ig-heart"></i>' + $(this).data("likes") + '<i class="ig-comment"></i>' + $(this).data("comments"));
        $('#ig-modal').modal();
    });

    $('body').on('click', '.video-holder', function (e) {
        window.open(
            $(currentSlide).data("links"),
            '_blank' // <- this is what makes it open in a new window.
            );
        return;
    });
    $('.ig-prev').on("click", function () {
        var current = $(currentSlide).parent().parent().prev().children().children();
        if (current[0] != null) {
            current.click();
        }
        else {
            $('.ig-btn').last().click();
        }
    })
    $('.ig-next').on("click", function () {
        var current = $(currentSlide).parent().parent().next().children().children();
        if (current[0] != null) {
            current.click();
        }
        else {
            $('.ig-btn').first().click();
        }
    })
        $("body").keydown(function (e) {
            if (e.keyCode == 37) { // left
                var current = $(currentSlide).parent().parent().prev().children().children();
                if (current[0] != null) {
                    current.click();
                }
                else {
                    $('.ig-btn').last().click();
                }
            }
            else if (e.keyCode == 39) { // right
                var current = $(currentSlide).parent().parent().next().children().children();
                if (current[0] != null) {
                    current.click();
                }
                else {
                    $('.ig-btn').first().click();
                }
            }
        });
    $('#ig-modal').on('hidden.bs.modal', function () {
        $('.ig-article-image').attr("src", "");
        $(".ig-description").html("");
    })
});
</script>