<?php
$images = $this->getBaseImagePath();
if ($items = $block->getBannerCollection()): ?>
    <div class="carousel-container">
        <div id="banner-slider-carousel">
            <?php $iterator = 1; ?>
            <div id="bannerslider-list-items-<?= $id =$block->getSliderId().'-'.uniqid(); ?>" class="owl-carousel owl-banner-carousel owl-bottom-narrow owl-bottom-absolute-narrow">
                <?php foreach ($items as $item): 
                    ?>
                    <?= ($iterator++ == 1) ? '<div class="banner-item banner-slider">' : '</div><div class="banner-item banner-slider">' ?>
                    <?php if ($item->getType() == 1): ?>
                    <div class="item-video">
                        <a class="owl-video" href="<?= $item->getUrlVideo() ?>"></a>
                    </div>
                    <?php elseif ($item->getType() == 2): ?>
                    <div class="item-content">
                        <?= $block->getPageFilter($item->getContent()); ?>
                    </div>
                    <?php else: ?>
                         <?php $sliderImage = $this->resize($item->getImage(),'600','500'); ?>
                    <div class="item" style="background:url(<?= $sliderImage ?>) center center no-repeat;background-size:cover;">
                        <div class="black-overlay">
                            <div class="container" style="position:relative">
                               <img src="<?= $sliderImage; ?>" alt="" />
                                <div class="content content-slide-2" style="">
                                    <p><span class="green-header"><?= $item->getTitle() ?></span></p>
                                    <?php if ($item->getSubtitle()): ?>
                                    <p class="big-gray-underline white-header"><span><?= $item->getSubtitle() ?></span></p>
                                    <?php endif; ?>
                                    <?php if ($item->getImageDescription()): ?>
                                    <p class="banner-subtitle"><?= $item->getImageDescription() ?></p>
                                    <?php endif; ?>
                                    <?php if ($item->getCtaText()): ?>
                                    <a href="<?= $item->getCtaLink() ?>" class="btn btn-default btn-red-slider" <?= ($item->getCtaTarget() == 1) ? 'target="_blank"' : '' ?>>
                                        <?= $item->getCtaText() ?>
                                    </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                    <?= ($iterator == count($items) + 1) ? '</div>' : '' ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?= $block->getPagerHtml() ?>
    </div>

    <script>
        require(['jquery', 'mageplaza/bannerslider/owlcarousel'], function ($) {
            $('#bannerslider-list-items-<?= $id; ?>').owlCarousel(<?php echo($block->getAllOptions())?>);
        });
    </script>
<?php endif; ?>
