<?php
	$categories = $this->getCategoryCollection();
	$canShowImg = $this->canShowImage();
?>
<div class="products wrapper grid products-grid">
   <div class="filterproducts products list items product-items owl-carousel ">
<?php foreach($categories as $category):?>
      <div class="item product product-item">
         <div class="product-item-info" data-container="product-grid">
            <div class="product photo product-item-photo">
							<?php if($canShowImg && $category->getImageUrl()):?>
               <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>" tabindex="-1">
							 <img class="product-image-photo default_image " src="<?php echo $block->escapeUrl($cat->getImageUrl()) ?>" alt=""/>
               
							 <!--<img class="product-image-photo hover_image" src="https://shopfecon.devphase.io/media/catalog/product/cache/5f1fe038290b55a4a54d9132509cd965/0/0/005-99-505.png" alt="FECON FLEECE JACKET, BLACK"/>
							 <img src="<?php echo $block->escapeUrl($cat->getImageUrl()) ?>" alt="" width="<?=$this->getImageWidth();?>" height="<?=$this->getImageHeight()?>"/>
							 -->
               </a>
							<?php endif;?>
            </div>
            <div class="product details product-item-details">
               <strong class="product name product-item-name">
               <a class="product-item-link"
                  href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
               <?php echo $block->escapeHtml($category->getName()) ?></a>
               </strong>
            </div>
         </div>
      </div>					
<?php	endforeach; ?>
   </div>
</div>