<?php
	$categories = $this->getCategoryCollection();
	$canShowImg = $this->canShowImage();
?>
<div class="products wrapper grid products-grid">
   <div class="filterproducts products list items product-items owl-carousel ">
<?php 
foreach($categories as $category):
	$catImageUrl = $this->getCategoryImage($category->getId());
?>
      <div class="item product product-item">
         <div class="product-item-info" data-container="product-grid">
            <div class="product photo product-item-photo">
							<?php if($canShowImg && $catImageUrl):?>
               <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>" tabindex="-1">
							 <img class="product-image-photo default_image " src="<?php echo $block->escapeUrl($catImageUrl) ?>" alt=""/>
               </a>
							<?php endif;?>
            </div>
            <div class="product details product-item-details">
               <strong class="product name product-item-name">
               <a class="product-item-link"
                  href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
               <?php echo $block->escapeHtml($category->getName()) ?></a>
               </strong>
            </div>
         </div>
      </div>					
<?php	endforeach; ?>
   </div>
</div>