<?php
/**
 * @copyright Copyright (c) Shop.Fecon.com, Inc. (http://shop.fecon.com)
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php $sytelineCompanyName = $block->getSytelineCompanyName($_order) ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()) : ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <address>
                        <?php if ($sytelineCompanyName !== "") : ?>
                            <?= $block->escapeHtml("{$sytelineCompanyName}") ?>
                            <?= "<br>" ?>
                        <?php endif; ?>
                        <?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?>
                    </address>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                </strong>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()) : ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else : ?>
                        <?= $block->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?php if ($sytelineCompanyName !== "") : ?>
                        <?= $block->escapeHtml("{$sytelineCompanyName}") ?>
                        <?= "<br>" ?>
                    <?php endif; ?>
                    <?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?>
                </address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
