<?php
function geocode($address) {
  // url encode the address
  $address = urlencode($address);
  // google map geocode api url
  $url = "http://maps.google.com/maps/api/geocode/json?address={$address}";
  // get the json response
  $resp_json = file_get_contents($url);
  // decode the json
  $resp = json_decode($resp_json, true);
  // response status will be 'OK', if able to geocode given address 
  if($resp['status'] == 'OK'){
    // get the important data
    $lati = $resp['results'][0]['geometry']['location']['lat'];
    $longi = $resp['results'][0]['geometry']['location']['lng'];
    $formatted_address = $resp['results'][0]['formatted_address'];
    // verify if data is complete
    if($lati && $longi && $formatted_address){
      // put the data in the array
      $data_arr = array();            
      array_push(
        $data_arr, 
        $lati, 
        $longi, 
        $formatted_address
        );
      return $data_arr;
    } else {
      return false;
    }
  } else {
    return false;
  }
}
$add_qry = $this->getstreet1().' '.$this->getstreet2().' '.$this->getcity().' '.$this->getregion().' '.$this->getzip().' '.$this->getcountry();
$data_arr = geocode($add_qry);
// if able to geocode the address
if($data_arr){
  $latitude = $data_arr[0];
  $longitude = $data_arr[1];
  $formatted_address = $data_arr[2];
} else {
  $latitude = 0;
  $longitude = 0;
  $formatted_address = '';
}
// $check_map = 	$this->isMapEnabled();
?>
<script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->getmapkey(); ?> "></script>
<?php 
$om = \Magento\Framework\App\ObjectManager::getInstance();
$obj = $om->get('Magento\Framework\HTTP\PhpEnvironment\RemoteAddress');
$ip =  $obj->getRemoteAddress();
//echo  $ip;
$xml = simplexml_load_file("http://www.geoplugin.net/xml.gp?ip=".$ip);
$country = $xml->geoplugin_countryName ;
?>
<script type="text/javascript">
require([
  'jquery',
  'jquery/ui',
  'mage/mage'
], function ($) {
  $('document').ready(function() {
    getCategories();
    /**
     * getCategories ajax function.
     * Function to get all categories.
     * 
     * @return {void} 
     */
    function getCategories() {
      var catUrl = '<?php echo $this->getcategoryajaxurl(); ?>';
      var param = '?ajax=1';
      $.ajax({
        showLoader: true,
        url: catUrl + param,
        type: "GET",
        dataType: 'json'
      }).done(function (data) {
        var dropdown = $('#category-dropdown');
        dropdown.empty();
        if(data.length != 0) {
          dropdown.append('<option selected="true" disabled>Choose Category</option>');
          dropdown.prop('selectedIndex', 0);
          var catAlreadyDisplayed = [];
          $.each(data, function (key, entry) {
            if(entry.entity_id != 1 && entry.entity_id != 2) {
              catAlreadyDisplayed.push(entry.entity_id);
              if(entry.children_count == 0) {
                dropdown.append($('<option></option>').attr('value', entry.entity_id).text(entry.name));
              }
              if(entry.children_count > 0 && !catAlreadyDisplayed.includes(entry.entity_id)) {
                dropdown.append($('<option></option>').attr('value', entry.entity_id).text(entry.name));
              }
            }
          });
        } else {
          dropdown.append('<option selected="true" disabled>No Available Categories</option>');
          dropdown.prop('selectedIndex', 0);
        }
      });
    }
    /**
     * getProducstByCategory ajax function.
     * Function to get all products under a specific category.
     * 
     * @param  {int} catId Category Id
     * @return {void}
     */
    function getProducstByCategory(catId) {
      var catUrl = '<?php echo $this->getproductsbycatajaxurl(); ?>';
      var param = '?cat=' + catId + '&ajax=1';
      $.ajax({
        showLoader: true,
        url: catUrl + param,
        type: "GET",
        dataType: 'json'
      }).done(function (data) {
        var dropdown = $('#product-dropdown');
        dropdown.empty();
        if(data.length != 0) {
          dropdown.append('<option selected="true" disabled>Choose Product</option>');
          dropdown.prop('selectedIndex', 0);
          $.each(data, function (key, entry) {
            dropdown.append($('<option></option>').attr('value', entry.entity_id).text(entry.name));
          });
        } else {
          dropdown.append('<option selected="true">No Available Products</option>');
          dropdown.prop('selectedIndex', 0);
        }
      });
    }

    var dataForm = $('#contact-form');   
    dataForm.mage('validation', {});

    /* Category dropdown change bind to fill products selector */
    $('#category-dropdown').change(function() {
      getProducstByCategory($(this).val());
    });
    /* Send select text instead of value */
    $('#contact-form').submit(function(){
      $('#category-dropdown option:selected').val(function(){
        return $(this).text().toUpperCase();
      });
      $('#product-dropdown option:selected').val(function(){
        return $(this).text().toUpperCase();
      });
    });
  });
});

function initialize() {
	var exists = document.getElementById("map");
 	var long = <?php echo $longitude; ?>//73.0373642;
	var lat = <?php echo $latitude; ?>//33.4819688;
	var myLatlng = new google.maps.LatLng(lat, long); // Change your location Latitude and Longitude 
	var mapOptions = {
    zoom: 14,
    center: myLatlng
  }
  var map = new google.maps.Map(document.getElementById('map'), mapOptions);
	// Disabled Map Scroll in Contact Page 
  map.setOptions({'scrollwheel': false});

	// Black and White style for Google Map
  var contentString = '<?php echo $add_qry; ?>';
  var infowindow = new google.maps.InfoWindow({
    content: contentString
  })
	// Google Map Maker 
  var marker = new google.maps.Marker({
    position: myLatlng,
    map: map,
  });
  marker.addListener('click', function() {
    infowindow.open(map, marker);
  });
}
</script>
<head>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <title>Info windows</title>
  </head>
  <body>
    <div class="main_block">
      <div class="map_container">
        <div class="page_title">
          <div class="aae-description">
            <?php echo $this->pagedescription(); ?>
          </div>
          <h2><?php echo $this->pageheading(); ?></h2>
        </div>
        <?php if($this->isMapEnabled() && $add_qry != '') { ?>
          <div class="map_block" id="map"></div>
          <div>
            <p>
          </div>
</div>
<?php } ?>
<div class="contact_container">
  <div class="inner_container">
    <ul>
      <?php if ($this->getphone() != '') {?>
        <li>
          <h3>Phone Number</h3>
          <p><?php echo $this->getphone(); ?>
            <br>
            <br></p>
          </li>
          <li class="divider"></li>
          <?php } ?>
          <?php if ($this->getStoreName() != '') { ?>
          <li> 
            <h3><?php echo $this->getStoreName(); ?></h3>
            <p><?php echo $this->getstreet1() . ' ' . $this->getstreet2() . ' ' . $this->getcity() . ',' . $this->getzip();?>
              <br>
              <br></p>
            </li>
            <li class="divider"></li>
            <?php } ?>
             <?php if ($this->getstoreemail() != '' && $this->getenableemailus() == true) { ?>
              <li class="last">
                <h3>Email Us</h3>
                <p><a href="#"><?php echo $this->getstoreemail(); ?></a>
                  <br>
                  <br></p>
                </li>
                <?php } ?>
              </ul>
            </div>
          </div>
          <div class="clear"></div>
          <div class="form_block">
            <div class="inner_container">
              <form class="form contact"
              action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
              id="contact-form"
              name="contact-form"
              onsubmit="return handle_recaptcha()"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
              <fieldset class="fieldset"> 
               <div>
                <div class="field select-category required input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>PRODUCT CATEGORY</label>
                  <select id="category-dropdown" name="product_category" class="category-select" data-validate="{required:true}"></select>
                </div>
                <div class="field select-product required input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>SELECT PRODUCT</label>
                  <select id="product-dropdown" name="product_name" class="product-select" data-validate="{required:true}"></select>
                </div>
                <div class="field select-question-about required input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>MY QUESTION IS ABOUT</label>
                  <select id="question-dropdown" name="question_about" class="question-select" data-validate="{required:true}">
                    <option selected="true" disabled>PLEASE SELECT ONE</option>
                    <option>PRODUCT SUPPORT</option>
                    <option>PARTS</option>
                    <option>CUSTOMER SERVICE</option>
                    <option>OTHER</option>
                  </select>
                </div>
                <div class="field select-hearabout required input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>HOW DID YOU HEAR ABOUT US?</label>
                  <select id="hearabout-dropdown" name="hear_about" class="hearabout-select" data-validate="{required:true}">
                    <option selected="true" disabled>PLEASE SELECT ONE</option>
                    <option>WEB SEARCH</option>
                    <option>FB/INSTAGRAM AD</option>
                    <option>TRADE SHOW</option>
                    <option>MAGAZINE</option>
                    <option>FECON DEALER/PARTNER</option>
                    <option>YOUTUBE AD</option>
                    <option>PRIOR KNOWLEDGE</option>
                    <option>WORD OF MOUTH</option>
                    <option>OTHER</option>
                  </select>
                </div> 
                <div class="field name required input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>NAME</label>
                  <div class="control">
                    <input name="name" id="name" placeholder="<?php /* @escapeNotVerified */ echo __($this->nametittle()) ?>" title="<?php /* @escapeNotVerified */ echo __($this->nametittle()) ?>"  class="input-text" type="text" data-validate="{required:true}"/>
                  </div>
                </div>
                <div class="field email required input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>EMAIL</label>
                  <div class="control">
                    <input name="email" id="email" placeholder="<?php /* @escapeNotVerified */ echo __($this->emailtittle()) ?>" title="<?php /* @escapeNotVerified */ echo __($this->emailtittle()) ?>"  class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                  </div>
                </div>
                <?php if($this->phonetittle() != '') {?>
                <div class="field telephone input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>PHONE NUMBER</label>
                  <div class="control">
                    <input name="phone" id="telephone" placeholder="<?php /* @escapeNotVerified */ echo __($this->phonetittle()) ?>" title="<?php /* @escapeNotVerified */ echo __($this->phonetittle()) ?>" class="input-text" type="text" data-validate="{required:true}" />
                  </div>
                </div>
                <?php } ?>

                <?php if($this->subjecttittle() != '') {?>
                <div class="field subject input_outer">
                  <label class="ask-expert-form-label"><span class="required">*</span>SUBJECT</label>
                  <div class="control">
                    <input name="subject" id="subject" placeholder="<?php /* @escapeNotVerified */ echo __($this->subjecttittle()) ?>" title="<?php /* @escapeNotVerified */ echo __($this->subjecttittle()) ?>" class="input-text" type="text" data-validate="{required:true}" />
                  </div>
                </div>
                <?php } ?>
              </div>
              <div class="field comment required">
              <div class="control">
                <textarea name="message" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __($this->messagetittle()) ?>" id="comment" title="<?php /* @escapeNotVerified */ echo __($this->messagetittle()) ?>" class="input-text" cols="1" rows="6" data-validate="{required:true}"></textarea>
              </div>
            </div>
            <?php if($this->isCaptchaEnabled()) { ?>
              <div class="g-recaptcha" name="recaptcha" id="recaptcha" data-sitekey="<?php echo $this->getsitekey(); ?>"></div>
              
              <?php } ?>
             <!-- <?php echo $block->getChildHtml('form.additional.info'); ?> -->
            </fieldset>
            <div class="actions-toolbar">
              <div class="primary">
                <input type="hidden" name="ip" id="ip" value="<?php echo $ip; ?>" />
                <input type="hidden" name="country" id="country" value="<?php echo $country; ?>" />
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" name="submit" id="submit"  title="<?php /* @escapeNotVerified */ echo __($this->buttontext()) ?>" class="action submit primary">
                  <span><?php /* @escapeNotVerified */ echo __($this->buttontext()) ?></span>
                </button>
              </div>
            </div>
          </form>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</body>