<?php
/**
 * @var $block \Fecon\Shipping\Block\Adminhtml\Preorder\Edit\CustomerInformation
 */
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Account Information')) ?></span>
        <div class="actions">
            <?php if ($customerUrl = $block->getCustomerViewUrl()) : ?>
                <a href="<?= /* @noEscape */ $block->getCustomerViewUrl() ?>" target="_blank">
                    <?= $block->escapeHtml(__('Edit Customer')) ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary order-account-information-table">
            <tr>
                <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                <td>
                    <?php if ($customerUrl = $block->getCustomerViewUrl()): ?>
                        <a href="<?= $block->escapeUrl($customerUrl) ?>" target="_blank">
                            <span><?= $block->escapeHtml($block->getCustomerName()) ?></span>
                        </a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getCustomerName()) ?>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Email')) ?></th>
                <td><a href="mailto:<?php echo $block->escapeHtml($block->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($block->getCustomerEmail()) ?></a></td>
            </tr>
            <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Customer Group')) ?></th>
                    <td><?= $block->escapeHtml($groupName) ?></td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</section>
