<?php
/**
 * @var $block \Fecon\Shipping\Block\Adminhtml\Preorder\Edit\Products
 */
$items = $block->getItems();
?>
<?php if ($items): ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Items Ordered') ?></span>
    </div>

    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= /* @noEscape */ __('Product') ?></span></th>
                    <th class="col-price"><span><?= /* @noEscape */ __('Price') ?></span></th>
                    <th class="col-ordered-qty"><span><?= /* @noEscape */ __('Qty') ?></span></th>
                    <th class="col-subtotal last"><span><?= /* @noEscape */ __('Subtotal') ?></span></th>
                </tr>
            </thead>

            <tbody>
                <?php $i = 0;
                foreach ($items as $item): ?>
                <?php  $i++; ?>
                <tr>
                    <td class="col-product">
                        <div class="product-title">
                            <?= $block->getProductName($item); ?>
                        </div>
                        <div class="product-sku-block">
                            <span>SKU:</span>
                            <?= $block->getSku($item); ?>
                        </div>
                    </td>
                    <td class="col-price">
                        <div class="price-excl-tax">
                            <?= $block->getPrice($item); ?>
                        </div>
                    </td>
                    <td class="col-ordered-qty">
                        <table class="qty-table">
                            <tbody>
                                <tr>
                                    <th>Ordered</th>
                                    <td><?= $block->getQty($item); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td class="col-subtotal">
                        <div class="price-excl-tax">
                            <span class="price"><?= $block->getSubtotal($item); ?></span>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

</section>
<?php endif; ?>