<div class="iwd_success_page_wrapper iwd_main_wrapper">
  <div class="iwd_opc_alternative_wrapper">
    <div class="iwd_opc_column iwd_opc_success_page_column">
      <div class="iwd_opc_alternative_column">
        <div class="iwd_opc_universal_wrapper iwd_opc_column_name">
          <h2>Thank you for your preorder!</h2>
          <p>You'll receive an email with instructions on how to proceed with your order</p>
          <hr />
          <div class="iwd_opc_universal_wrapper">
              <a href="<?php echo $block->getUrl(); ?>"
                 class="iwd_opc_button <?php if ($block->isCustomerLoggedIn()) { ?>active<?php } ?>"
                 title="<?php echo __('Continue Shopping'); ?>">
                  <?php echo __('Continue Shopping'); ?>
              </a>
          </div>
          <?php if ($block->isCustomerLoggedIn()) { ?>
              <div class="iwd_opc_universal_wrapper">
                  <a href="<?php echo $block->getCustomerAccountUrl(); ?>"
                     class="iwd_opc_button"
                     title="<?php echo __('My Account'); ?>">
                      <?php echo __('My Account'); ?>
                  </a>
              </div>
          <?php } ?>
        </div>
      </div>
    </div>
  </div>
</div>
