<div class="iwd_success_page_wrapper iwd_main_wrapper">
  <div class="iwd_opc_alternative_wrapper">
    <div class="iwd_opc_column iwd_opc_success_page_column">
      <div class="iwd_opc_alternative_column">
        <div class="iwd_opc_universal_wrapper iwd_opc_column_name">
          <h1>Quote requested successfully</h1>
          <p>You'll receive an email with instructions on how to proceed with your order</p>
          <hr />
          <p>Check my <a href="/sales/order/history/">orders history</a></p>
          <p>Go to <a href="/customer/account/">my account</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
