<?php

// @codingStandardsIgnoreFile
/** @var \Fecon\SytelineIntegration\Pricing\Render\Amount $block */
?>
<?php
if ($block->shouldReloadPrice()):
    $ajaxurl = $block->getRenderPriceEndpointUrl();
    $currentProductId = $block->getSaleableItem()->getId();
?>
<?php /** Do not display price, display a loader instead, price will be loaded with Ajax */ ?>
<!-- Begin loading icon -->
<div class="sk-circle"> <div class="sk-circle1 sk-child"></div><div class="sk-circle2 sk-child"></div><div class="sk-circle3 sk-child"></div><div class="sk-circle4 sk-child"></div><div class="sk-circle5 sk-child"></div><div class="sk-circle6 sk-child"></div><div class="sk-circle7 sk-child"></div><div class="sk-circle8 sk-child"></div><div class="sk-circle9 sk-child"></div><div class="sk-circle10 sk-child"></div><div class="sk-circle11 sk-child"></div><div class="sk-circle12 sk-child"></div></div>
<!-- End loading icon -->
<div class="price-loader-messsage">
    <span>Retrieving your price</span>
</div>
<div id="ajaxresponse"></div>
<script type="text/x-magento-init">
        {
            ".price-loader-messsage": {
                "Fecon_SytelineIntegration/js/reload-price": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>",
                    "productId": "<?php echo $currentProductId; ?>"
                }
            }
        }
</script>

<?php else: ?>
<?php /** Display price normally */ ?>
<span class="price-container <?= /* @escapeNotVerified */ $block->getAdjustmentCssClasses() ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>
      <?php /* echo $block->shouldReloadPrice() ? "data-mage-init='{\"loader\": {}}'" : '' */ ?>>
    <?php if ($block->getDisplayLabel()): ?>
        <span class="price-label"><?= /* @escapeNotVerified */ $block->getDisplayLabel() ?></span>
    <?php endif; ?>
    <span <?php if ($block->getPriceId()): ?> id="<?= /* @escapeNotVerified */ $block->getPriceId() ?>"<?php endif;?>
        <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
        data-price-amount="<?= /* @escapeNotVerified */ $block->getDisplayValue() ?>"
        data-price-type="<?= /* @escapeNotVerified */ $block->getPriceType() ?>"
        class="price-wrapper <?= /* @escapeNotVerified */ $block->getPriceWrapperCss() ?>">
        <?= /* @escapeNotVerified */ $block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()) ?>
    </span>
    <?php if ($block->hasAdjustmentsHtml()): ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="price" content="<?= /* @escapeNotVerified */ $block->getDisplayValue() ?>" />
        <meta itemprop="priceCurrency" content="<?= /* @escapeNotVerified */ $block->getDisplayCurrencyCode() ?>" />
    <?php endif; ?>
</span>

<?php endif; ?>
